server:
  port: 8080
spring:
  application:
    name: Elearning
  datasource:
    url: jdbc:mysql://localhost:3306/elearning
    username: springstudent
    password: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        enable_lazy_load_no_trans: true
        format_sql: true
    show-sql: true

api:
  prefix: /api/v1